name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/loom-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 25

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: runDatagen
        run: ./gradlew runDatagen
      - name: compress png
        run: chmod +x ./oxipng/oxipng && ./oxipng/oxipng -o max -s -a -r src
      - name: build
        run: ./gradlew build
        env:
          RELEASE: true
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
      - name: Build and publish with Gradle
        run: ./gradlew runDatagen build publish
        env:
          MODRINTH: ${{ secrets.MODRINTH }}
          CHANGELOG: ${{ github.event.release.body }}
          RELEASE: true
